service: library-api
provider: 
   name: aws
   runtime: nodejs14x
   region: ap-southeast-2

custom:
    bucketName: myserverlessprojectuploadbucket-123123123


functions:
graphql: 
  handler: LIBRARY-API/index.default
  timeout: 90
  events:
  - http:
     path: graphql
     method: post
     cors:
       origin: '*'
       headers: 
       - Content-type
       allowCredentials: false
   