service: library-api
provider: 
   name: aws
   runtime: nodejs14x
   region: ap-southeast-2

custom:
    bucketName: library-api-state


functions:
  graphql: 
    handler: LIBRARY-API/index.default
    events:
     - http:
         path: graphql
         method: post
         cors:
           origin: '*'
           headers: 
              - Content-type
           allowCredentials: false